# configuration for pre-commit git hooks

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: debug-statements
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v1.3.1
  hooks:
    # Run the linter.
    - id: ruff
    # Run the formatter.
    - id: ruff-format