[project]
name = "fauxfactory"
version = "3.1.1"
license = { text = "Apache-2.0" }
description = "Generates random data for your tests."
authors = [
    { name = "Og B. Maciel", email = "omaciel@ogmaciel.com" }
]
dependencies = [
    "black>=24.3.0",
    "flake8>=7.0.0",
    "sphinx>=7.1.2",
    "codecov>=2.1.13",
    "pytest>=8.1.1",
    "pytest-cov>=5.0.0",
    "wheel>=0.43.0",
    "twine>=5.0.0",
    "setuptools>=69.2.0",
]
readme = "README.rst"
requires-python = ">= 3.8"

keywords = [
  "automation",
  "data",
  "python",
  "testing",
]
classifiers = [
        "Development Status :: 5 - Production/Stable",
        "Intended Audience :: Developers",
        "Natural Language :: English",
        "License :: OSI Approved :: Apache Software License",
        "Operating System :: OS Independent",
        "Programming Language :: Python",
        "Programming Language :: Python :: 3.9",
        "Programming Language :: Python :: 3.10",
        "Programming Language :: Python :: 3.11",
        "Programming Language :: Python :: 3.12",
        "Topic :: Software Development :: Testing",
]

[project.urls]
Changelog = "https://github.com/omaciel/fauxfactory/blob/main/HISTORY.rst"
Homepage = "https://github.com/omaciel/fauxfactory"


[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.rye]
managed = true
dev-dependencies = []

[tool.hatch.metadata]
allow-direct-references = true

[tool.hatch.build.targets.wheel]
packages = ["fauxfactory"]
macos-max-compat = true

[tool.black]
line-length = 100
skip-string-normalization = true
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.hg
  | \.mypy_cache
  | \.venv
  | _build
  | buck-out
  | build
  | dist
)/
'''
