name: Fauxfactory Checks

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11", "3.12"]

    steps:
      - uses: actions/checkout@v4
      - name: Install a specific version
        uses: eifinger/setup-rye@v2
      - name: Install dependencies
        run: |
          rye sync
      - name: Pre Commit Checks
        uses: pre-commit/action@v3.7.0
      - name: Run checks
        run: |
          make all
      - name: Upload Coverage to Codecov
        uses: codecov/codecov-action@v1
